## STATIC CONFIG (restart traefik to update)

# shows you a log msg if a newer image tag can be used
global:
  checkNewVersion: true

# log default is ERROR, but WARN is more helpful
log:
  # level: WARN
  # level: INFO
  level: DEBUG
  filePath: "/var/logs/traefik/traefik.log"

# enable dashboard on 8080 with NO AUTH
api:
  dashboard: true
  insecure: false

# enable ping so the `traefik healthcheck` works
ping: {}

# auto-proxy containers if they have proper labels
# and also use this file for dynamic config (tls)
providers:
  docker:
    exposedByDefault: false
    watch: true
    # endpoint: "unix:///var/run/docker.sock"
    swarmMode: true

  file:
    fileName: /etc/traefik/dynamic.yaml
    watch: true

# listen on 80/443, and redirect all 80 to 443 via 301
entryPoints:
  web:
    address: :80
    # comment out these lines if you don't want to redirect everything
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443


certificatesResolvers:
  letsencrypt:
    acme:
      email: dporto@gsd.inesc-id.pt
      storage: /certs/acme.json
      # production
      caserver: https://acme-v02.api.letsencrypt.org/directory  
      # staging
      # caserver: https://acme-staging-v02.api.letsencrypt.org/directory

      # httpChallenge --------------------------------------------------
        # used during the challenge
        # entryPoint: web

      #dns challenge ---------------------------------------------------
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
